### ISSUE TITLE
[1.18.2] Temperature support is broken for Cold Sweat

### ISSUE THREAD

**Issue by DeshiDesu** [EtherealOnyx/Parties#169]
`sedparties-1.18.2-1.0.2` used with `ColdSweat-2.2`, getting the following chat message:

```
[Parties] Cold Sweat version not supported! Support has been disabled.
```

**Comment by EtherealOnyx** [comment]
I will take a look at this, thanks.

**Comment by DeshiDesu** [comment]
[latest.log](https://github.com/EtherealOnyx/Parties/files/12733081/latest.log)

Seems caused by
```
Caused by: java.lang.ClassNotFoundException: dev.momostudios.coldsweat.config.ClientSettingsConfig
```

**Comment by EtherealOnyx** [comment]
Looks like they reorganized things a bit internally. Thanks for the quick report, I will fix this immediately.

**Comment by EtherealOnyx** [comment]
Version 1.0.3 has been released with a fix for this [here](https://legacy.curseforge.com/minecraft/mc-mods/parties/files/4770692)

Note that new mechanics have been added with the way thermometers and temperature work in Cold Sweat version 2.2. As of now, my mod disables the thermometer requirement to be able to function properly. I will re-implement support in the next version to make use of these new features.

Thanks for the again for the report!
